"""Short-term conversation memory management for Friday agent."""

from __future__ import annotations

from typing import Any


class ConversationMemory:
    """Manages short-term conversation message history and sliding window context."""

    def __init__(
        self,
        system_prompt: str | None = None,
        max_messages: int = 50,
    ) -> None:
        """Initialize ConversationMemory.

        Args:
            system_prompt: Optional initial system prompt.
            max_messages: Maximum number of non-system messages to retain.
        """
        self.system_prompt = system_prompt
        self.max_messages = max_messages
        self._messages: list[dict[str, Any]] = []

    def set_system_prompt(self, prompt: str | None) -> None:
        """Set or update the system prompt.

        Args:
            prompt: New system prompt string or None to remove.
        """
        self.system_prompt = prompt

    def add_user_message(self, content: str) -> None:
        """Add a user message to history.

        Args:
            content: User message text.
        """
        self._messages.append({"role": "user", "content": content})
        self._enforce_max_messages()

    def add_assistant_message(
        self,
        content: str | None = None,
        tool_calls: list[dict[str, Any]] | None = None,
    ) -> None:
        """Add an assistant response to history.

        Args:
            content: Assistant response text or None.
            tool_calls: Optional list of tool calls generated by LLM.
        """
        msg: dict[str, Any] = {"role": "assistant", "content": content}
        if tool_calls is not None:
            msg["tool_calls"] = tool_calls
        self._messages.append(msg)
        self._enforce_max_messages()

    def add_tool_result(self, tool_call_id: str, content: str) -> None:
        """Add a tool execution result to history.

        Args:
            tool_call_id: Unique ID of tool call.
            content: Tool result string.
        """
        self._messages.append(
            {
                "role": "tool",
                "tool_call_id": tool_call_id,
                "content": content,
            }
        )
        self._enforce_max_messages()

    def get_messages(self) -> list[dict[str, Any]]:
        """Return complete list of messages including system prompt if present.

        Returns:
            List of message dictionaries compatible with LLM providers.
        """
        full_list: list[dict[str, Any]] = []
        if self.system_prompt is not None and self.system_prompt.strip():
            full_list.append({"role": "system", "content": self.system_prompt.strip()})
        full_list.extend(self._messages)
        return full_list

    def clear(self) -> None:
        """Clear conversation history (keeps system prompt)."""
        self._messages.clear()

    def _enforce_max_messages(self) -> None:
        """Trim message history if it exceeds max_messages."""
        if len(self._messages) > self.max_messages:
            excess = len(self._messages) - self.max_messages
            self._messages = self._messages[excess:]

    def __len__(self) -> int:
        """Return count of non-system messages."""
        return len(self._messages)
