"""Short-term conversation memory management for Friday agent."""

from __future__ import annotations

import json
import threading
import time
from pathlib import Path
from typing import Any


class ConversationMemory:
    """Manages short-term conversation message history and sliding window context."""

    def __init__(
        self,
        system_prompt: str | None = None,
        max_messages: int = 50,
        chat_id: str | None = None,
        save_dir: Path | None = None,
    ) -> None:
        """Initialize ConversationMemory.

        Args:
            system_prompt: Optional initial system prompt.
            max_messages: Maximum number of non-system messages to retain.
            chat_id: Optional ID to save/load this chat.
            save_dir: Directory where chats are saved.
        """
        self.system_prompt: str | None = system_prompt
        self.max_messages = max_messages
        self.chat_id = chat_id or "default"
        self.save_dir = save_dir
        self.title = "New Chat"
        self.workspace: str = ""
        self._messages: list[dict[str, Any]] = []
        self._on_change_callbacks: list[Any] = []
        self._lock = threading.RLock()

        if self.save_dir:
            self.save_dir.mkdir(parents=True, exist_ok=True)
            self.load()

    def add_on_change_callback(self, callback: Any) -> None:
        """Add a callback to be called when messages change."""
        self._on_change_callbacks.append(callback)

    def _trigger_on_change(self) -> None:
        """Trigger all on_change callbacks."""
        import inspect

        for cb in self._on_change_callbacks:
            try:
                sig = inspect.signature(cb)
                if len(sig.parameters) >= 1:
                    cb(self)
                else:
                    cb()
            except Exception:
                pass

    def set_system_prompt(self, prompt: str | None) -> None:
        """Set or update the system prompt.

        Args:
            prompt: New system prompt string or None to remove.
        """
        self.system_prompt = prompt

    def add_user_message(self, content: str) -> None:
        """Add a user message to history.

        Args:
            content: User message text.
        """
        import uuid

        with self._lock:
            self._messages.append(
                {"id": uuid.uuid4().hex, "role": "user", "content": content}
            )
            self._enforce_max_messages()
            self._save_unsafe()
        self._trigger_on_change()

    def add_assistant_message(
        self,
        content: str | None = None,
        tool_calls: list[dict[str, Any]] | None = None,
    ) -> None:
        """Add an assistant response to history.

        Args:
            content: Assistant response text or None.
            tool_calls: Optional list of tool calls generated by LLM.
        """
        import uuid

        msg: dict[str, Any] = {
            "id": uuid.uuid4().hex,
            "role": "assistant",
            "content": content,
        }
        if tool_calls is not None:
            msg["tool_calls"] = tool_calls
        with self._lock:
            self._messages.append(msg)
            self._enforce_max_messages()
            self._save_unsafe()
        self._trigger_on_change()

    def add_tool_result(self, tool_call_id: str, content: str) -> None:
        """Add a tool execution result to history.

        Args:
            tool_call_id: Unique ID of tool call.
            content: Tool result string.
        """
        import uuid

        with self._lock:
            self._messages.append(
                {
                    "id": uuid.uuid4().hex,
                    "role": "tool",
                    "tool_call_id": tool_call_id,
                    "content": content,
                }
            )
            self._enforce_max_messages()
            self._save_unsafe()
        self._trigger_on_change()

    @property
    def current_chat_id(self) -> str:
        return self.chat_id

    def add_message(self, role: str, content: str, chat_id: str | None = None) -> None:
        """Add a raw message to history.

        Ignores chat_id since we only have one active chat.
        """
        import uuid

        if role == "user":
            self.add_user_message(content)
        elif role == "assistant":
            self.add_assistant_message(content)
        elif role == "system":
            with self._lock:
                self._messages.append(
                    {"id": uuid.uuid4().hex, "role": "system", "content": content}
                )
                self._enforce_max_messages()
                self._save_unsafe()
            self._trigger_on_change()

    def truncate_messages(self, message_id: str, inclusive: bool = False) -> None:
        """Truncate history up to the specified message ID."""
        with self._lock:
            idx = next(
                (i for i, m in enumerate(self._messages) if m.get("id") == message_id),
                -1,
            )
            if idx != -1:
                self._messages = self._messages[: idx + (1 if inclusive else 0)]
                self._save_unsafe()
        self._trigger_on_change()

    def get_chat(self, chat_id: str) -> dict[str, Any]:
        """Return the current chat in the format expected by the UI."""
        with self._lock:
            messages = self.get_messages()
            title = self.title
            workspace = self.workspace
            current_id = self.chat_id
        return {
            "id": current_id,
            "title": title,
            "workspace": workspace,
            "updated_at": int(time.time()),
            "messages": messages,
        }

    def get_messages(self, inject_system: bool = True) -> list[dict[str, Any]]:
        """Return complete list of messages including system prompt if present.

        Args:
            inject_system: Ignored, kept for backward compatibility.
        """
        full_list: list[dict[str, Any]] = []

        if self.system_prompt is not None and self.system_prompt.strip():
            prompt_text = self.system_prompt.strip()

            if self.workspace:
                prompt_text += f"\n\n[System Info]\nActive Workspace: {self.workspace}\nYou are operating in this specific project directory. File paths should be relative to this directory."
            else:
                prompt_text += "\n\n[System Info]\nActive Workspace: None (No Project)\nYou are operating in the default global environment."

            full_list.append({"role": "system", "content": prompt_text})

        with self._lock:
            full_list.extend(self._messages)

        return full_list

    def clear(self) -> None:
        """Clear conversation history (keeps system prompt)."""
        with self._lock:
            self._messages.clear()
            self._save_unsafe()
        self._trigger_on_change()

    def _enforce_max_messages(self) -> None:
        """Trim message history if it exceeds max_messages."""
        if len(self._messages) > self.max_messages:
            excess = len(self._messages) - self.max_messages
            self._messages = self._messages[excess:]

    def __len__(self) -> int:
        """Return count of non-system messages."""
        with self._lock:
            return len(self._messages)

    def load(self) -> None:
        if not self.save_dir:
            return
        file_path = self.save_dir / f"{self.chat_id}.json"
        if file_path.exists():
            try:
                with open(file_path, encoding="utf-8") as f:
                    data = json.load(f)
                    with self._lock:
                        self._messages = data.get("messages", [])
                        self.title = data.get("title", "New Chat")
                        self.workspace = data.get("workspace", "")
            except Exception:
                pass

    def save(self) -> None:
        with self._lock:
            self._save_unsafe()

    def _save_unsafe(self) -> None:
        if not self.save_dir:
            return
        # Generate title from first user message if title is default
        if self.title == "New Chat":
            for msg in self._messages:
                if msg.get("role") == "user":
                    self.title = msg.get("content", "New Chat")[:30] + (
                        "..." if len(msg.get("content", "")) > 30 else ""
                    )
                    break

        file_path = self.save_dir / f"{self.chat_id}.json"
        data = {
            "id": self.chat_id,
            "title": self.title,
            "workspace": self.workspace,
            "updated_at": int(time.time()),
            "messages": self._messages,
        }
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
        except Exception:
            pass

    def switch_chat(self, new_id: str) -> None:
        with self._lock:
            self.chat_id = new_id
            self._messages.clear()
            self.title = "New Chat"
            self.workspace = ""
            self.load()

    def get_all_chats(self) -> list[dict[str, Any]]:
        if not self.save_dir:
            return []
        chats = []
        with self._lock:
            for file_path in self.save_dir.glob("*.json"):
                try:
                    with open(file_path, encoding="utf-8") as f:
                        data = json.load(f)
                        chats.append(
                            {
                                "id": data.get("id"),
                                "title": data.get("title", "New Chat"),
                                "updated_at": data.get("updated_at", 0),
                            }
                        )
                except Exception:
                    pass
        return sorted(chats, key=lambda x: x["updated_at"], reverse=True)

    def rename_chat(self, chat_id: str, new_title: str) -> None:
        if not self.save_dir:
            return
        with self._lock:
            file_path = self.save_dir / f"{chat_id}.json"
            if file_path.exists():
                try:
                    with open(file_path, encoding="utf-8") as f:
                        data = json.load(f)
                    data["title"] = new_title
                    with open(file_path, "w", encoding="utf-8") as f:
                        json.dump(data, f, ensure_ascii=False, indent=2)
                    # If we are renaming the active chat, update the title in memory
                    if self.chat_id == chat_id:
                        self.title = new_title
                except Exception:
                    pass

    def delete_chat(self, chat_id: str) -> None:
        if not self.save_dir:
            return
        with self._lock:
            file_path = self.save_dir / f"{chat_id}.json"
            if file_path.exists():
                try:
                    file_path.unlink()
                    # If we delete the active chat, reset state
                    if self.chat_id == chat_id:
                        self.chat_id = "default"
                        self._messages.clear()
                        self.title = "New Chat"
                        self.workspace = ""
                        self.load()
                except Exception:
                    pass
